Example for DMA side-channel attack
sancus-tee/sancus-examples pull request #13
Opened 2020-03-17 13:14 UTC by martonbognar

This example showcases how an attacker can differentiate secret-dependent control flows using the DMA-capable attacker peripheral and sancus-step. (Very similar to the sancus-step example.)

Currently only a draft PR, because the implementation might still change depending on changes in the attacker peripheral or sancus-step.

Any comments or requests are welcome!

2020-03-23 12:26 UTC, jovanbulck requested changes
Nice job! :+1: I left some comments for further improvements in the code :)

2020-03-23 12:26 UTC, jovanbulck commented on dma-side-channel/main.c
> +uint16_t **dma_addr     = (uint16_t**) 0x0070;
probably makes sense to have these MMIO addresses as constants in a header file in sancus-support? eg have a look at the tsc peripheral example? If we decided to move the peripheral in the address space we'll only have to update one file ^^

2020-03-23 12:26 UTC, jovanbulck commented on dma-side-channel/main.c
> +        if (*dma_trace & 0x80) {
also better to have this a s a constant maybe? cf above it mentions bit 0x40

2020-03-23 12:26 UTC, jovanbulck commented on dma-side-channel/main.c
> +    delay = __ss_isr_reti_latency + DELAY_BEFORE_SM;
hm I think it would be preferable to keep this stable for the future if compilers might change etc --> better to integrate this configuration directly into sancus-step? Like configure the DMA delay directly in assembly in the sancus-step code instead of here w a "magic" DELAY_BEFORE_SM value that depends on the compiler-generated code for this C code? Seems possible to me?

2020-03-23 12:26 UTC, jovanbulck commented on dma-side-channel/main.c
> +        if (*dma_trace & 0x80) {
also in general here I think it would be preferable and cleaner and more stable to fully separate the side-channel *harvesting* code from the *interpretation*, i.e., focus in the C code here only on configuring the peripheral dumping all the side-channel trace on stdout; then afterwards in a "post-processing" script you can derive the application secret from the trace using a simple regex or more robust Python script or so ^^

Have a look at some of the Nemesis sancus-step examples:

https://github.com/jovanbulck/nemesis/blob/master/sancus/stubs/multiplication-stub/leak.py

2020-03-27 02:22 UTC, martonbognar commented on dma-side-channel/main.c
> +uint16_t **dma_addr     = (uint16_t**) 0x0070;
Pull request submitted for the changes in sancus-support: https://github.com/sancus-pma/sancus-support/pull/10

2020-03-27 02:25 UTC, martonbognar commented on dma-side-channel/main.c
> +        if (*dma_trace & 0x80) {
I agree, I extracted the mask to a constant, but it feels like a post-processing script would be very overkill for this example, where we only need to compare a single bit. (And this way, it's also analogous to the sancus-step example.)

2020-03-30 08:50 UTC, jovanbulck commented on dma-side-channel/main.c
> +        if (*dma_trace & 0x80) {
oka sounds good

2020-03-30 08:52 UTC, jovanbulck requested changes

2020-03-30 08:52 UTC, jovanbulck commented on dma-side-channel/main.c
> +    DMA_COUNTDOWN = delay;
why is this still necessary? Is the idea not to do this all transparently in the sancus-step asm framework code?

2020-03-30 08:52 UTC, jovanbulck commented on dma-side-channel/main.c
> +    __ss_set_dma_attacker_delay(0);
ideally this call shoudln't be needed, could be part of ss_init?

2020-03-30 13:57 UTC, martonbognar commented on dma-side-channel/main.c
> +    DMA_COUNTDOWN = delay;
You're right, setting the delay from here actually has no effect, this was left over from the previous implementation.

2020-07-08 17:18 UTC, merged